spring.application.name=smp-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/smp_db
spring.datasource.username=postgres
spring.datasource.password=DortmundKamen26
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
server.port=8080